services:
  ha:
    container_name: ha
    image: homeassistant/home-assistant:2024.12.5
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./data/ha/config:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mosquitto

  hass-configurator:
    container_name: hass-configurator
    image: causticlab/hass-configurator-docker:0.5.2
    restart: unless-stopped
    ports:
      - "3218:3218/tcp"
    environment:
      - HC_BASEPATH=/hass-config
      - HC_USERNAME=${HASS_CONFIGURATOR_USERNAME}
      - HC_PASSWORD=${HASS_CONFIGURATOR_PASSWORD}
      - HC_DIRSFIRST=true
    volumes:
      - ./data/hass-configurator/config:/config
      - ./data/ha/config:/hass-config

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.20
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.42.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Moscow
    devices:
      - ${ZIGBEE_ADAPTER_TTY}:/dev/ttyACM0
    volumes:
      - ./data/zigbee2mqtt/app/data:/app/data
      - /run/udev:/run/udev:ro
    depends_on:
      - mosquitto
