services:
  ha:
    container_name: ha
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
