services:
  ha:
    container_name: ha
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./data/ha/config:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mosquitto

  hass-configurator:
    container_name: hass-configurator
    image: causticlab/hass-configurator-docker
    restart: unless-stopped
    ports:
      - "3218:3218/tcp"
    environment:
      - HC_BASEPATH=/hass-config
      - HC_USERNAME=${HASS_CONFIGURATOR_USERNAME}
      - HC_PASSWORD=${HASS_CONFIGURATOR_PASSWORD}
      - HC_DIRSFIRST=true
    volumes:
      - ./data/hass-configurator/config:/config
      - ./data/ha/config:/hass-config

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883/tcp"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log
