
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

command_line:
  - sensor:
      unique_id: rpi.cpu.temperature
      name: CPU Temperature
      command: 'cat /sys/class/thermal/thermal_zone0/temp'
      unit_of_measurement: 'C'
      scan_interval: 60
      value_template: '{{ value | multiply(0.001) | round(3) }}'
